### ISSUE TITLE
Nightly Features

### ISSUE THREAD

**Issue by mmstick** [anowell/promptly#1]
You may want to add a disclaimer that this requires a nightly version of Rust. I'm currently limited to using Rust 1.24.1 for the projects that I do for work, so that it can get packaged into a Debian repo, so this is off limits for now.

**Comment by anowell** [comment]
I dropped the ball on responding, but the nightly requirement was dropped in 388e539b for 0.1.5 by putting the specialization bits behind a feature flag.
