### ISSUE TITLE
Return `Result` instead of exiting process

### ISSUE THREAD

**Issue by pwoolcoc** [anowell/promptly#2]
It would be nice for the various `prompt` functions/methods to return `Result<T, io::Error>` instead of exiting the process on an error

**Comment by anowell** [comment]
Agreed. Will look into this soon, but the error will probably be more like [ReadlineError](https://docs.rs/rustyline/5.0.5/rustyline/error/enum.ReadlineError.html) than just `io::Error`

**Comment by anowell** [comment]
Finally got around to this for 0.3 (along with a few other API simplifications).

Note, bumping the version and simply propagating the error to `fn main` does result in slightly different output as the error gets `Debug` printed, and that includes printing `Error: Interrupted` when using Ctrl+C (which was previously silently swallowed). I might play around with reworking the error type to have a custom (similarly opinionated) `Termination` implementation - but `Termination` isn't stable yet, so not in any rush.
