### ISSUE TITLE
error[E0277] when compiling (dead simple String input as let)

### ISSUE THREAD

**Issue by SamPro910** [anowell/promptly#5]
Hello!

I am a beginner in Rust. When I try to run
`let name: String = prompt("Enter your name")?;`
I get ``error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `Try`)``

**Comment by Xavientois** [comment]
What is the return type of the function in which you are calling prompt?

**Comment by SwiftDust** [comment]
@Xavientois I have the same error. What do you have to write at the brackets in `fn main()`?

**Comment by Xavientois** [comment]
> I have the same error. What do you have to write at the brackets in fn main()?

The `main` function in Rust can return a `Result`. For example, you can make your `main` function signature the following:

```Rust
fn main() -> Result<(), Box<dyn std::error::Error>> { ... }
```

This will allow you to use the `?` operator on any function call that returns a `Result<T, E>` where `E` implements the standard library `Error` trait. Example [here](https://github.com/voiceflow/api-examples/blob/c3d8ba9ee8eced7ec8d241973b1eb0284aaec212/rust/src/main.rs#L34).

What I prefer to do is to use the [`Result`](https://docs.rs/anyhow/latest/anyhow/type.Result.html) trait from the `anyhow` crate. It functions in much the same way, but without the verbosity of writing `Box<dyn std::error::Error>`.

Hope this helps!

**Comment by SwiftDust** [comment]
Thanks very much! This helps me alot!

**Comment by SwiftDust** [comment]
One more thing, how do you use this with `match`? I tried something but that gave me an error...

```
match prompt_user {
    //When true, create a new note
    Some(true) => {
        //Create a new note
        create_new_note();
        Ok(())
    }

    //When false, exit the program
    Some(false) => {
        //Exit the program
        println!("Nevermind, see you next time :)");
        Ok(())
    }   
}
```

**Comment by Xavientois** [comment]
@ThatBoiDev Assuming you're calling `prompt` to get `prompt_user`, it is returning a `Result`, not an `Option`. In your `match` statement, you are matching the variants from `Option` (`Some(T)` and `None`). You will likely want to match on the variants of `Result`, which are `Ok(T)` and `Err(E)`.

Based on your code, it would look something like this:
```Rust
let prompt_user = prompt("Do you want to create a new note?"); // <-- Notice that there is no `?` operator at the end
match prompt_user {
  Ok(true) => {
    //Create a new note
    create_new_note();
    Ok(())
  }
  Ok(false) => {
     //Exit the program
     println!("Nevermind, see you next time :)");
     Ok(())
  }
  Err(e) => {
    // Error handling
  }
}
```

If you just want to allow the calling function to do the error handling (or to fail if it's `main`), then you can use the `?` operator on your call to `prompt`:
```Rust
let prompt_user = prompt("Do you want to create a new note?")?; // <-- Notice the `?` operator
if prompt_user {
    create_new_note();
} else {
     println!("Nevermind, see you next time :)");
}
Ok(())
```

Remember that when you are using a `match` statement, you need to match on every possible variant. In an `Option` that would be `Some(T)` and `None`. The book has a good explanation on it, if you want to learn more about it: https://doc.rust-lang.org/book/ch06-02-match.html

**Comment by SwiftDust** [comment]
You're awesome!! Sorry that I interrupted you but you give really nice help. Again thank you a lot
